# Generated by Django 5.0.6 on 2024-06-16 18:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textual_genre', models.CharField(blank=True, choices=[('reportagem', 'Reportagem'), ('noticia', 'Notícia'), ('artigo', 'Artigo'), ('fanfic', 'Fanfic'), ('conto', 'Conto'), ('resenha', 'Resenha'), ('receita', 'Receita'), ('resumo', 'Resumo'), ('tirinha', 'Tirinha'), ('charge', 'Charge')], max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(choices=[('saude', 'Saúde'), ('opiniao', 'Opinião'), ('mundo', 'Mundo'), ('brasil', 'Brasil'), ('culinaria', 'Culinária'), ('cultura_lazer', 'Cultura e Lazer'), ('esportes', 'Esportes'), ('enem', 'Enem'), ('professor', 'Professor')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('subtitle', models.CharField(max_length=80)),
                ('main_text', models.TextField()),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('post_views', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
                ('textual_genre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.genre')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('section_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.section')),
            ],
        ),
    ]
