# Generated by Django 5.0.6 on 2024-09-01 22:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='textual_genre',
            field=models.CharField(blank=True, choices=[('reportagem', 'Reportagem'), ('noticia', 'Notícia'), ('artigo', 'Artigo'), ('fanfic', 'Fanfic'), ('conto', 'Conto'), ('resenha', 'Resenha'), ('receita', 'Receita'), ('cronica', 'Crônica'), ('resumo', 'Resumo'), ('tirinha', 'Tirinha')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'bmp', 'tiff', 'webp', 'svg'])]),
        ),
        migrations.AlterField(
            model_name='section',
            name='section_name',
            field=models.CharField(choices=[('saude', 'Saúde'), ('opiniao', 'Opinião'), ('mundo', 'Mundo'), ('brasil', 'Brasil'), ('cultura_lazer', 'Cultura e Lazer'), ('enem', 'Enem'), ('professor', 'Professor')], max_length=50),
        ),
    ]
