# Generated by Django 5.0.6 on 2024-05-27 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_delete_posts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textual_genre', models.CharField(choices=[('reportagem', 'Reportagem'), ('noticia', 'Notícia'), ('artigo_opiniao', 'Artigo de opinião'), ('fanfic', 'Fanfic')], max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='textual_genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.genre'),
        ),
    ]
