# Generated by Django 5.0.6 on 2024-05-29 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_post_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='textual_genre',
            field=models.CharField(choices=[('reportagem', 'Reportagem'), ('noticia', 'Notícia'), ('opiniao', 'Texto de opinião'), ('fanfic', 'Fanfic'), ('jogos', 'Jogos'), ('receitas', 'Receitas')], max_length=30),
        ),
    ]
