# Generated by Django 5.0.6 on 2024-05-29 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_genre_textual_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='textual_genre',
            field=models.CharField(choices=[('reportagem', 'Reportagem'), ('noticia', 'Notícia'), ('artigo', 'Artigo de opinião'), ('fanfic', 'Fanfic'), ('conto', 'Conto'), ('resenha', 'Jogos'), ('receitas', 'Receitas'), ('resumo', 'Resumo')], max_length=30),
        ),
    ]
