# Generated by Django 5.0.6 on 2024-09-23 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_section_subsection_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='textual_genre',
            field=models.CharField(blank=True, choices=[('reportagem', 'Reportagem'), ('noticia', 'Notícia'), ('artigo', 'Artigo'), ('fanfic', 'Fanfic'), ('conto', 'Conto'), ('resenha', 'Resenha'), ('receita', 'Receita'), ('cronica', 'Crônica'), ('resumo', 'Resumo'), ('tirinha', 'Tirinha'), ('ilustracao', 'Ilustracao')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='subsection_name',
            field=models.CharField(blank=True, choices=[('literatura', 'Literatura'), ('cinema_tv', 'Cinema e TV'), ('games', 'Jogos'), ('comida', 'Comida'), ('artes', 'Artes dos alunos')], max_length=50, null=True),
        ),
    ]
