# Generated by Django 5.0.6 on 2024-05-30 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_genre_textual_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='textual_genre',
            field=models.CharField(choices=[('reportagem', 'Reportagem'), ('noticia', 'Notícia'), ('artigo', 'Artigo de opinião'), ('fanfic', 'Fanfic'), ('conto', 'Conto'), ('resenha', 'Resenha'), ('receitas', 'Receitas'), ('resumo', 'Resumo')], max_length=30),
        ),
    ]
