# Generated by Django 5.0.6 on 2024-09-23 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_genre_textual_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='textual_genre',
            field=models.CharField(blank=True, choices=[('reportagem', 'Reportagem'), ('noticia', 'Notícia'), ('artigo', 'Artigo'), ('fanfic', 'Fanfic'), ('conto', 'Conto'), ('resenha', 'Resenha'), ('receita', 'Receita'), ('cronica', 'Crônica'), ('resumo', 'Resumo'), ('tirinha', 'Tirinha'), ('ilustracao', 'Ilustração')], max_length=30, null=True),
        ),
    ]
