# Generated by Django 5.0.6 on 2024-05-31 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_sections_post_section_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sections',
            new_name='Section',
        ),
    ]
