# Generated by Django 5.0.6 on 2024-05-31 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_rename_sections_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='section_name',
            field=models.CharField(choices=[('enem', 'Enem'), ('professor', 'Professor'), ('entretenimento', 'Entretenimento'), ('saude', 'Saúde'), ('opiniao', 'Opinião'), ('mundo', 'Mundo')], max_length=50),
        ),
    ]
