# Generated by Django 5.0.6 on 2024-05-31 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_alter_section_section_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='section_name',
            field=models.CharField(choices=[('entretenimento', 'Entretenimento'), ('saude', 'Saúde'), ('opiniao', 'Opinião'), ('mundo', 'Mundo')], max_length=50),
        ),
    ]
