# Generated by Django 5.0.6 on 2024-05-31 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_alter_section_section_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='textual_genre',
            field=models.CharField(blank=True, choices=[('reportagem', 'Reportagem'), ('noticia', 'Notícia'), ('artigo', 'Artigo de opinião'), ('fanfic', 'Fanfic'), ('conto', 'Conto'), ('resenha', 'Resenha'), ('receitas', 'Receitas'), ('resumo', 'Resumo')], max_length=30),
        ),
    ]
