# Generated by Django 5.0.6 on 2024-05-31 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_alter_genre_textual_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='textual_genre',
            field=models.CharField(blank=True, choices=[('reportagem', 'Reportagem'), ('noticia', 'Notícia'), ('artigo', 'Artigo de opinião'), ('fanfic', 'Fanfic'), ('conto', 'Conto'), ('resenha', 'Resenha'), ('receitas', 'Receitas'), ('resumo', 'Resumo')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='section_name',
            field=models.CharField(choices=[('entretenimento', 'Entretenimento'), ('saude', 'Saúde'), ('opiniao', 'Opinião'), ('mundo', 'Mundo'), ('brasil', 'Brasil')], max_length=50),
        ),
    ]
