# Generated by Django 5.0.6 on 2024-10-16 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_asking_for_illustration',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
