# Generated by Django 5.0.6 on 2024-10-16 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_post_is_asking_for_illustration'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_illustration_done',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
