# Generated by Django 5.0.6 on 2024-06-01 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_alter_post_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='section_name',
            field=models.CharField(choices=[('saude', 'Saúde'), ('opiniao', 'Opinião'), ('mundo', 'Mundo'), ('brasil', 'Brasil'), ('gastronomia', 'Gastronomia'), ('cultura_lazer', 'Cultura e Lazer'), ('esportes', 'Esportes'), ('enem', 'Enem'), ('professor', 'Professor')], max_length=50),
        ),
    ]
