# Generated by Django 5.0.6 on 2024-10-18 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_post_illustrator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='main_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='subtitle',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
