# Generated by Django 5.0.6 on 2024-10-22 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_alter_post_main_text_alter_post_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subtitle_illustrator',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
