# Generated by Django 5.0.6 on 2024-06-04 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='columnist',
            field=models.BooleanField(default=False),
        ),
    ]
