# Generated by Django 5.0.6 on 2024-06-04 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_post_columnist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='columnist',
        ),
    ]
