# Generated by Django 5.0.6 on 2024-11-17 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_post_subtitle_illustrator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='section_name',
            field=models.CharField(choices=[('saude', 'Saúde'), ('opiniao', 'Opinião'), ('mundo', 'Mundo'), ('brasil', 'Brasil'), ('cultura_lazer', 'Cultura e Lazer'), ('enem', 'Enem'), ('professor', 'Professor'), ('redacao', 'Redação')], max_length=50),
        ),
    ]
