# Generated by Django 5.0.6 on 2024-06-04 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_remove_post_columnist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='textual_genre',
            field=models.CharField(blank=True, choices=[('reportagem', 'Reportagem'), ('noticia', 'Notícia'), ('artigo', 'Artigo'), ('fanfic', 'Fanfic'), ('conto', 'Conto'), ('resenha', 'Resenha'), ('receita', 'Receita'), ('resumo', 'Resumo'), ('tirinha', 'tirinha'), ('charge', 'Charge')], max_length=30, null=True),
        ),
    ]
