# Generated by Django 5.0.4 on 2024-12-18 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_chapter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['chapter_number']},
        ),
        migrations.RenameField(
            model_name='chapter',
            old_name='order',
            new_name='chapter_number',
        ),
    ]
