# Generated by Django 5.0.6 on 2025-03-03 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0022_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='subsection_name',
            field=models.CharField(blank=True, choices=[('literatura', 'Literatura'), ('cinema_tv', 'Cinema e TV'), ('games', 'Jogos'), ('comida', 'Comida'), ('ilustracoes', 'Ilustrações')], max_length=50, null=True),
        ),
    ]
