# Generated by Django 5.0.6 on 2024-06-16 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiBncc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cur_comp', models.CharField(blank=True, choices=[('arte', 'Arte'), ('geografia', 'Geografia'), ('historia', 'História'), ('lingua_portuguesa', 'Língua Portuguesa'), ('lingua_inglesa', 'Língua Inglesa'), ('educacao_fisica', 'Educação Física'), ('ciencias', 'Ciências'), ('ensino_religioso', 'Ensino Religioso'), ('matematica', 'Matemática')], max_length=40, null=True)),
                ('thema_unities', models.CharField(blank=True, max_length=90, null=True)),
                ('k_obj', models.CharField(blank=True, max_length=510, null=True)),
                ('whole_skill', models.CharField(max_length=1610, null=True)),
                ('cod_skill', models.CharField(max_length=10, null=True)),
                ('skill', models.CharField(max_length=1610)),
                ('field_act', models.CharField(blank=True, max_length=40, null=True)),
                ('lang_prac', models.CharField(blank=True, max_length=150, null=True)),
                ('axis', models.CharField(blank=True, max_length=40, null=True)),
                ('es1', models.BooleanField()),
                ('es2', models.BooleanField()),
                ('es3', models.BooleanField()),
                ('es4', models.BooleanField()),
                ('es5', models.BooleanField()),
                ('es6', models.BooleanField()),
                ('es7', models.BooleanField()),
                ('es8', models.BooleanField()),
                ('es9', models.BooleanField()),
            ],
        ),
    ]
