# Generated by Django 5.0.6 on 2024-06-15 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiBncc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cur_comp', models.CharField(max_length=40)),
                ('k_obj', models.CharField(max_length=300)),
                ('skill', models.CharField(max_length=400)),
                ('description', models.CharField(max_length=500)),
                ('es1', models.BooleanField()),
                ('es2', models.BooleanField()),
                ('es3', models.BooleanField()),
                ('es4', models.BooleanField()),
                ('es5', models.BooleanField()),
                ('es6', models.BooleanField()),
                ('es7', models.BooleanField()),
                ('es8', models.BooleanField()),
                ('es9', models.BooleanField()),
            ],
        ),
    ]
