# Generated by Django 5.0.6 on 2024-08-18 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_bncc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElementarySchoolBncc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cur_comp', models.CharField(blank=True, choices=[('arte', 'Arte'), ('geografia', 'Geografia'), ('historia', 'História'), ('lingua_portuguesa', 'Língua Portuguesa'), ('lingua_inglesa', 'Língua Inglesa'), ('educacao_fisica', 'Educação Física'), ('ciencias', 'Ciências'), ('ensino_religioso', 'Ensino Religioso'), ('matematica', 'Matemática')], max_length=40, null=True)),
                ('thema_unities', models.CharField(blank=True, max_length=90, null=True)),
                ('k_obj', models.CharField(blank=True, max_length=510, null=True)),
                ('whole_skill', models.CharField(max_length=1610, null=True)),
                ('cod_skill', models.CharField(max_length=10, null=True)),
                ('skill', models.CharField(max_length=1610)),
                ('field_act', models.CharField(blank=True, max_length=40, null=True)),
                ('lang_prac', models.CharField(blank=True, max_length=150, null=True)),
                ('axis', models.CharField(blank=True, max_length=40, null=True)),
                ('es1', models.BooleanField()),
                ('es2', models.BooleanField()),
                ('es3', models.BooleanField()),
                ('es4', models.BooleanField()),
                ('es5', models.BooleanField()),
                ('es6', models.BooleanField()),
                ('es7', models.BooleanField()),
                ('es8', models.BooleanField()),
                ('es9', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='HighSchoolBncc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cur_comp', models.CharField(blank=True, max_length=40, null=True)),
                ('whole_skill', models.CharField(max_length=1610, null=True)),
                ('cod_skill', models.CharField(max_length=10, null=True)),
                ('skill', models.CharField(max_length=1610)),
                ('field_act', models.CharField(blank=True, max_length=40, null=True)),
                ('es10', models.BooleanField(blank=True, null=True)),
                ('es11', models.BooleanField(blank=True, null=True)),
                ('es12', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_level', models.CharField(max_length=2)),
            ],
        ),
        migrations.DeleteModel(
            name='ApiBncc',
        ),
        migrations.AddField(
            model_name='highschoolbncc',
            name='school_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_bncc.schoollevel'),
        ),
        migrations.AddField(
            model_name='elementaryschoolbncc',
            name='school_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_bncc.schoollevel'),
        ),
    ]
