# Generated by Django 5.0.6 on 2024-06-15 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_bncc', '0002_alter_apibncc_description_alter_apibncc_k_obj_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apibncc',
            name='k_obj',
            field=models.CharField(max_length=1000),
        ),
    ]
