# Generated by Django 5.0.6 on 2024-08-18 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_bncc', '0002_elementaryschoolbncc_highschoolbncc_schoollevel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elementaryschoolbncc',
            name='school_level',
        ),
        migrations.RemoveField(
            model_name='highschoolbncc',
            name='school_level',
        ),
        migrations.DeleteModel(
            name='SchoolLevel',
        ),
    ]
