# Generated by Django 5.0.6 on 2024-06-15 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_bncc', '0003_alter_apibncc_k_obj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apibncc',
            name='skill',
            field=models.CharField(max_length=2000),
        ),
    ]
