# Generated by Django 5.0.6 on 2024-08-19 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_bncc', '0004_alter_highschoolbncc_cur_comp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highschoolbncc',
            name='cur_comp',
            field=models.CharField(blank=True, choices=[('linguagens', 'Linguagens'), ('matematica', 'Matemática'), ('lingua_portuguesa', 'Língua Portuguesa'), ('ciencias_humanas', 'Ciências Humanas'), ('ciencias_da_natureza', 'Ciências da Natureza')], max_length=40, null=True),
        ),
    ]
