# Generated by Django 5.0.6 on 2024-06-16 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_bncc', '0005_alter_apibncc_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apibncc',
            name='cur_comp',
            field=models.CharField(blank=True, choices=[('arte', 'Arte'), ('geografia', 'Geografia'), ('historia', 'História'), ('portugues', 'Língua Portuguesa'), ('ingles', 'Língua Inglesa'), ('educacao_fisica', 'Educação Física'), ('ciencias', 'Ciências'), ('ensino_religioso', 'Ensino Religioso'), ('matematica', 'Matemática')], max_length=40, null=True),
        ),
    ]
