# Generated by Django 5.0.6 on 2024-06-16 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_bncc', '0006_alter_apibncc_cur_comp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apibncc',
            name='description',
        ),
        migrations.AddField(
            model_name='apibncc',
            name='axis',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='apibncc',
            name='code_skill',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='apibncc',
            name='field_act',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='apibncc',
            name='lang_prac',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='apibncc',
            name='thema_unities',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='apibncc',
            name='whole_skill',
            field=models.CharField(max_length=1600, null=True),
        ),
        migrations.AlterField(
            model_name='apibncc',
            name='cur_comp',
            field=models.CharField(blank=True, choices=[('arte', 'Arte'), ('geografia', 'Geografia'), ('historia', 'História'), ('lingua_portuguesa', 'Língua Portuguesa'), ('lingua_inglesa', 'Língua Inglesa'), ('educacao_fisica', 'Educação Física'), ('ciencias', 'Ciências'), ('ensino_religioso', 'Ensino Religioso'), ('matematica', 'Matemática')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='apibncc',
            name='k_obj',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='apibncc',
            name='skill',
            field=models.CharField(max_length=1600),
        ),
    ]
