# Generated by Django 5.0.6 on 2024-06-16 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_bncc', '0007_remove_apibncc_description_apibncc_axis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apibncc',
            name='skill',
            field=models.CharField(max_length=1610),
        ),
    ]
