# Generated by Django 5.0.6 on 2024-06-16 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_bncc', '0008_alter_apibncc_skill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apibncc',
            old_name='code_skill',
            new_name='cod_skill',
        ),
    ]
