# Generated by Django 5.0.6 on 2024-07-16 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='text',
        ),
        migrations.AddField(
            model_name='question',
            name='context',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
