# Generated by Django 5.0.6 on 2024-07-16 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_alter_question_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='created',
        ),
        migrations.RemoveField(
            model_name='question',
            name='created',
        ),
        migrations.RemoveField(
            model_name='question',
            name='quiz',
        ),
    ]
