# Generated by Django 5.0.6 on 2024-07-17 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_alter_question_quiz_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='coluna_extra',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
