# Generated by Django 5.0.6 on 2024-07-17 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_question_coluna_extra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='coluna_extra',
        ),
    ]
