# Generated by Django 5.0.6 on 2024-07-17 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0014_remove_answer_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='isCorrect',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
