# Generated by Django 5.0.6 on 2024-07-17 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0018_remove_answer_iscorrect'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='isCorrect',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.question'),
        ),
    ]
