# Generated by Django 5.0.6 on 2024-07-17 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0020_remove_answer_iscorrect'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
    ]
