# Generated by Django 5.0.6 on 2024-07-18 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0023_remove_answer_alternative_remove_answer_right_answer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='is_correct',
        ),
    ]
