# Generated by Django 5.0.6 on 2024-07-18 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0024_remove_answer_is_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_correct',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
