# Generated by Django 5.0.6 on 2024-07-24 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0025_answer_is_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_imag',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
