# Generated by Django 5.0.6 on 2024-07-24 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0026_question_question_imag'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
