# Generated by Django 5.0.6 on 2024-07-24 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0027_question_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_imag',
            field=models.CharField(blank=True, max_length=290, null=True),
        ),
    ]
