# Generated by Django 5.0.6 on 2024-07-24 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0028_alter_question_question_imag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_imag',
            new_name='question_image',
        ),
    ]
