# Generated by Django 5.0.6 on 2024-07-24 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0030_question_subject'),
        ('quizes', '0010_quizsubject_quiz_subject_hum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='quiz_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quizes.quizsubject'),
        ),
    ]
