# Generated by Django 5.0.6 on 2024-07-24 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0031_alter_question_quiz_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='context',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(blank=True, max_length=1700, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_image',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
