# Generated by Django 5.0.6 on 2024-07-24 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0033_alter_question_question_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='subject',
        ),
    ]
