# Generated by Django 5.0.6 on 2024-07-27 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0034_remove_question_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_image',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
