# Generated by Django 5.0.6 on 2024-07-30 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0036_question_has_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(blank=True, max_length=1705, null=True),
        ),
    ]
