# Generated by Django 5.0.6 on 2024-07-30 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0037_alter_question_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='has_image_alt',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.CharField(max_length=2500),
        ),
    ]
