# Generated by Django 5.0.6 on 2024-07-30 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0038_answer_has_image_alt_alter_answer_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
