# Generated by Django 5.0.6 on 2024-08-11 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0039_alter_question_question_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='alternative',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
