# Generated by Django 5.0.6 on 2024-08-11 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0040_question_alternative'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='alternative',
        ),
    ]
