# Generated by Django 5.0.6 on 2024-08-11 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0041_remove_question_alternative'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='alternative',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
