# Generated by Django 5.0.6 on 2024-08-12 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0042_answer_alternative'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.CharField(max_length=2501),
        ),
    ]
