# Generated by Django 5.0.6 on 2024-09-30 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0043_alter_answer_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answer_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
