# Generated by Django 5.0.4 on 2024-12-13 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0045_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='selected_correct',
            new_name='is_selected_answer_correct',
        ),
    ]
