# Generated by Django 5.0.4 on 2024-12-13 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0046_rename_selected_correct_score_is_selected_answer_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='is_correct',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
