# Generated by Django 5.0.4 on 2024-12-13 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0047_score_is_correct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Score',
        ),
    ]
