# Generated by Django 5.0.4 on 2024-12-22 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0048_delete_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='examining_board',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='spec_subject',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='spec_topic',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
