# Generated by Django 5.0.4 on 2024-12-27 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0050_remove_question_spec_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(blank=True, max_length=1706, null=True),
        ),
    ]
