# Generated by Django 5.0.6 on 2025-01-07 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0052_alter_question_question_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(blank=True, max_length=1705, null=True),
        ),
    ]
