# Generated by Django 5.0.6 on 2025-01-08 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0055_alter_question_question_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='number',
        ),
        migrations.RemoveField(
            model_name='question',
            name='spec_topic',
        ),
    ]
