# Generated by Django 5.0.6 on 2025-01-08 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0057_remove_question_has_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_image',
            field=models.ImageField(blank=True, null=True, upload_to='quizes/images/answers'),
        ),
    ]
