# Generated by Django 5.0.6 on 2025-01-08 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0058_alter_answer_answer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.CharField(blank=True, max_length=2501, null=True),
        ),
    ]
