# Generated by Django 5.0.6 on 2025-01-08 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0059_alter_answer_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='has_image_alt',
        ),
    ]
