# Generated by Django 5.0.6 on 2024-06-05 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_is_columnist'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='presentation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
