# Generated by Django 5.0.6 on 2024-06-05 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_presentation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='presentation',
            field=models.CharField(default='membro da equipe', max_length=100),
            preserve_default=False,
        ),
    ]
