# Generated by Django 5.0.6 on 2024-09-28 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_user_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_artist',
            field=models.BooleanField(default=False),
        ),
    ]
