# Generated by Django 5.0.6 on 2024-10-07 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customuser_is_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_x',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_youtube',
            field=models.URLField(blank=True, null=True),
        ),
    ]
