# Generated by Django 5.0.6 on 2024-10-07 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_customuser_user_instagram_customuser_user_linkedin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='user_x',
            new_name='user_facebook',
        ),
    ]
