# Generated by Django 5.0.6 on 2024-10-11 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_rename_user_x_customuser_user_facebook'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_essay_editor',
            field=models.BooleanField(default=False),
        ),
    ]
