# Generated by Django 5.0.6 on 2024-10-14 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_customuser_is_essay_editor'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_premium',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
