# Generated by Django 5.0.6 on 2024-10-19 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_customuser_is_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='has_accepted_terms',
            field=models.BooleanField(default=False),
        ),
    ]
