# Generated by Django 5.0.4 on 2024-12-13 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_customuser_has_accepted_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='total_correct_answers',
            field=models.IntegerField(default=0),
        ),
    ]
