# Generated by Django 5.0.4 on 2024-12-13 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_customuser_total_correct_answers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='total_correct_answers',
        ),
    ]
