# Generated by Django 5.0.6 on 2024-10-11 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_essay', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EssayGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c1', models.IntegerField()),
                ('about_c1', models.CharField(max_length=300)),
                ('c2', models.IntegerField()),
                ('about_c2', models.CharField(max_length=300)),
                ('c3', models.IntegerField()),
                ('about_c3', models.CharField(max_length=300)),
                ('c4', models.IntegerField()),
                ('about_c4', models.CharField(max_length=300)),
                ('c5', models.IntegerField()),
                ('about_c5', models.CharField(max_length=300)),
                ('essay_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review_essay.essay')),
            ],
        ),
    ]
