# Generated by Django 5.0.6 on 2024-10-12 11:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_essay', '0004_alter_essaygrade_about_c1_alter_essaygrade_about_c2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='essay',
            name='about_c1',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='essay',
            name='c1',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(200)]),
        ),
        migrations.DeleteModel(
            name='EssayGrade',
        ),
    ]
