# Generated by Django 5.0.6 on 2024-10-12 14:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_essay', '0005_essay_about_c1_essay_c1_delete_essaygrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='essay',
            name='about_c2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='essay',
            name='about_c3',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='essay',
            name='about_c4',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='essay',
            name='about_c5',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='essay',
            name='c2',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(200)]),
        ),
        migrations.AddField(
            model_name='essay',
            name='c3',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(200)]),
        ),
        migrations.AddField(
            model_name='essay',
            name='c4',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(200)]),
        ),
        migrations.AddField(
            model_name='essay',
            name='c5',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(200)]),
        ),
    ]
