# Generated by Django 5.0.6 on 2024-10-12 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review_essay', '0007_essay_reviewed_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='essay',
            old_name='reviewed_image',
            new_name='correction_image',
        ),
    ]
