# Generated by Django 5.0.6 on 2024-10-13 15:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_essay', '0009_alter_essay_correction_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='essay',
            name='audio_feedback',
            field=models.FileField(blank=True, null=True, upload_to='audio/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'ogg'])]),
        ),
    ]
