# Generated by Django 5.0.6 on 2024-10-14 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_essay', '0010_essay_audio_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='essay',
            name='total_grade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
