# Generated by Django 5.0.6 on 2024-10-15 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_essay', '0011_essay_total_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='essay',
            name='is_finished',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
