# Generated by Django 5.0.6 on 2024-11-08 23:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_essay', '0013_alter_essay_correction_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essay',
            name='correction_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'bmp', 'tiff', 'webp', 'svg'])]),
        ),
    ]
