# Generated by Django 5.0.6 on 2024-11-11 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_essay', '0014_alter_essay_correction_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essay',
            name='is_finished',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
