# Generated by Django 5.0.6 on 2024-11-13 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_essay', '0015_alter_essay_is_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='essay',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
