# Generated by Django 5.0.6 on 2024-11-13 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_essay', '0016_essay_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essay',
            name='created',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
