# Generated by Django 5.0.6 on 2024-07-15 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0003_alter_quiz_required_score_to_pass_alter_quiz_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('easy', 'easy'), ('medium', 'medium'), ('hard', 'hard')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='number_of_questions',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='required_score_to_pass',
            field=models.IntegerField(blank=True, help_text='Pontuação requerida em %', null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='time',
            field=models.IntegerField(blank=True, help_text='Duração em minutos', null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='topic',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
