# Generated by Django 5.0.6 on 2024-07-16 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0004_alter_quiz_difficulty_alter_quiz_number_of_questions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='difficulty',
        ),
    ]
