# Generated by Django 5.0.6 on 2024-07-16 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0005_remove_quiz_difficulty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='number_of_questions',
        ),
    ]
