# Generated by Django 5.0.6 on 2024-07-16 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0006_remove_quiz_number_of_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_subject', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Quizes',
            },
        ),
    ]
