# Generated by Django 5.0.6 on 2024-07-16 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_question_quiz_subject'),
        ('quizes', '0007_quizsubject'),
        ('results', '0002_alter_result_quiz'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
