# Generated by Django 5.0.6 on 2024-07-16 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0008_delete_quiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizsubject',
            name='text',
        ),
    ]
