# Generated by Django 5.0.6 on 2024-07-18 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0009_remove_quizsubject_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsubject',
            name='quiz_subject_hum',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='quizsubject',
            name='quiz_subject',
            field=models.CharField(max_length=25),
        ),
    ]
