# Generated by Django 5.0.6 on 2024-09-30 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0010_quizsubject_quiz_subject_hum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsubject',
            name='quiz_created_by',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
