# Generated by Django 5.0.6 on 2024-07-15 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnemDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('context', models.CharField(max_length=4000)),
                ('question', models.CharField(max_length=1500)),
                ('alt_a', models.CharField(max_length=1500)),
                ('alt_b', models.CharField(max_length=1500)),
                ('alt_c', models.CharField(max_length=1500)),
                ('alt_d', models.CharField(max_length=1500)),
                ('alt_e', models.CharField(max_length=1500)),
                ('correct', models.CharField(max_length=1)),
                ('context_images', models.CharField(max_length=500)),
                ('subject', models.CharField(max_length=10)),
                ('year', models.IntegerField()),
            ],
        ),
    ]
