# Generated by Django 5.0.6 on 2024-07-16 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enem_db', '0002_alter_enemdb_alt_e'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enemdb',
            name='alt_e',
            field=models.CharField(max_length=1500),
        ),
    ]
