# Generated by Django 5.0.6 on 2024-07-16 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enem_db', '0003_alter_enemdb_alt_e'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enemdb',
            name='alt_a',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='enemdb',
            name='alt_b',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='enemdb',
            name='alt_c',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='enemdb',
            name='alt_d',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='enemdb',
            name='alt_e',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='enemdb',
            name='context',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='enemdb',
            name='context_images',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='enemdb',
            name='correct',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='enemdb',
            name='question',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
