# Generated by Django 5.0.6 on 2024-07-17 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enem_db', '0004_alter_enemdb_alt_a_alter_enemdb_alt_b_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enemdb',
            old_name='subject',
            new_name='subject_code',
        ),
    ]
