# Generated by Django 5.0.6 on 2024-07-17 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enem_db', '0005_rename_subject_enemdb_subject_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='enemdb',
            name='subject',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='enemdb',
            name='subject_code',
            field=models.IntegerField(),
        ),
    ]
