# Generated by Django 5.0.6 on 2024-07-17 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enem_db', '0006_enemdb_subject_alter_enemdb_subject_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enemdb',
            name='subject_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
