# Generated by Django 5.0.6 on 2024-07-27 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enem_db', '0007_alter_enemdb_subject_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enemdb',
            name='context_images',
        ),
        migrations.AddField(
            model_name='enemdb',
            name='question_image',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
